### ISSUE TITLE
NaN sometimes

### ISSUE THREAD

**Issue by cburgdorfer** [HappehBunneh/gravio_gauge#2]
@maxjay Sometimes, it shows NaN in the Dashboard, supposlingly if the timing is wrong.

![image](https://user-images.githubusercontent.com/311968/53840607-7871a680-3f92-11e9-885b-ce41a45f6216.png)

**Comment by maxjay** [comment]
Could you copy what the console says

**Comment by cburgdorfer** [comment]
It turns out the ```data``` field sometimes contained the path to the image file rather than the number of people.

a ```filter``` for ```NumberOfPeople``` in the ```DataType``` parameter solved the problem.
